site_name: ZJU-CS
repo_name: ZJU-CS/CourseNotes
repo_url: https://github.com/ZJU-CS/CourseNotes
edit_uri: blob/main/docs

copyright: 'Copyright &copy 2024 ZJU-CS'

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
  icon:
    repo: fontawesome/brands/github-alt
    edit: material/pencil
    view: material/eye
  custom_dir: overrides

markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  - admonition
  - pymdownx.details
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
  - search:
      separator: '[\s\-\.]+'
  - statistics:
      words_per_minute: 200
  - glightbox

extra_css:
  # 如果需要修改主题样式，可以修改 `theme.css`；如果需要修改 admonitions 的主题，可以修改 `admonitions.css`
  - supports/css/base.css
  - supports/css/theme.css
  - supports/css/admonitions.css
  # 如果公式渲染样式出现问题，请检查如下脚本
  - https://jsd.cdn.zzko.cn/npm/katex@0.16.4/dist/katex.min.css

extra_javascript:
  # 自动令所有第三方链接在新标签页中打开
  - supports/js/xlink.js
  # 如果公式渲染出现问题，请检查如下脚本
  - supports/js/katex.js
  - https://jsd.cdn.zzko.cn/npm/katex@0.16.4/dist/katex.min.js

# ======================================== >>>

nav:
  - index.md
  - "数字逻辑设计":
    - "Main":
      - digital_design/index.md
      - digital_design/1-x.md
      - digital_design/2-x.md
      - digital_design/3-x.md
      - digital_design/4-x.md
      - digital_design/5-x.md
      - digital_design/6-x.md
      - digital_design/7-x.md
    # - "Appendix":
  - "计算机组成":
    - "Main":
      - computer_organization/index.md
      - computer_organization/1-x.md
      - computer_organization/2-x.md
      - computer_organization/3-x.md
      - computer_organization/4-x.md
      - computer_organization/5-x.md
      - computer_organization/6-x.md
    - "Appendix":
      - computer_organization/A-exams.md
  - "操作系统":
    - "Main":
      - operating_system/index.md
      - operating_system/0-x.md
      - operating_system/1-x.md
      - "2.x 同步 | Synchronization":
        - operating_system/2-1-x.md
        - operating_system/2-2-x.md
        - operating_system/2-3-x.md
      - "3.x 内存 | Memory":
        - operating_system/3-1-x.md
        - operating_system/3-2-x.md
      - operating_system/4-x.md
      - operating_system/5-x.md
      - operating_system/6-x.md
    # - "Appendix":



# ======================================== <<<

